SHELL := /bin/bash

all:
	(cd ..; raku -I. ./sbin/m*u g)

e:
	(cd ..; raku -I. ./sbin/m*u e)
d:
	(cd ..; raku -I. ./sbin/m*u g d)

dr:
	(cd ..; raku -I. ./sbin/dr*u g l d)

help:
	(cd ..; raku -I. ./sbin/dr*u)
