unit class Yevent;

# WARNING - Auto-generated by Raku module 'CSV-Autoclass'
#
#           Author: Tom Browder (IRC #raku and Github name 'tbrowder')
#
# Local edits may be accidentally lost by a careless user of 'CSV-Autoclass'
# and its installed executable program 'csv2class'.

has $.day   is rw = '';
has $.mon   is rw = '';
has $.type  is rw = '';
has $.name  is rw = '';
has $.year  is rw = '';
has $.notes is rw = '';

method new($day, $mon, $type, $name, $year, $notes) {

    self.bless(:$day, :$mon, :$type, :$name, :$year, :$notes)

}

#| Special multi methods allow setting attribute values
#| programmatically via a special single method

#| Getter multi methods
multi method day()     { $!day   }       
multi method mon()     { $!mon   }       
multi method type()    { $!type  }       
multi method name()    { $!name  }       
multi method year()    { $!year  }       
multi method notes()   { $!notes }       

#| Setter multi methods
multi method day($v)   { $!day    = $v }
multi method mon($v)   { $!mon    = $v }
multi method type($v)  { $!type   = $v }
multi method name($v)  { $!name   = $v }
multi method year($v)  { $!year   = $v }
multi method notes($v) { $!notes  = $v }

#| Special methods

#| Set a value programmatically
method set-value(:$field!, :$value!) {
    self."$field"($value)
}

#| Return a list of the the attributes (fields) of the class instance
method list-fields(--> List) {
    my @attrs = self.^attributes;
    my @nams;
    for @attrs -> $a {
        #| Need to get its name.  The name is prefixed by its
        #| sigil and twigil which we don't want.
        my $v = $a.name;
        $v ~~ s/\S\S//;
        @nams.push: $v;
    }
    @nams
}

#| Return a list of the values for the attributes of the class instance
method list-values(--> List) {
    my @attrs = self.^attributes;
    my @vals;
    for @attrs -> $a {
        # need to get its value
        my $v = $a.get_value: self;
        @vals.push: $v;
    }
    @vals
}

#===============================================================
# End of CSV-Autoclass definition of class '$cname'
#===============================================================
