name: MacOS

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macos-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Special Dependencies (no sudo, no '-y' with brew)
        run: |
          brew install cpanminus 
          cpanm --sudo Astro::MoonPhase Astro::Utils Astro::Montenbruck Datetime::Format::StrpTime
      - name: Install Dependencies
        run: |
          zef install --/test Test::Output
          zef install --/test --deps-only .
          zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
